spring.application.name=lms-backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/foliopath360_lms
spring.datasource.username=root
spring.datasource.password=Mammu@1412
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


# JWT Configuration
jwt.secret=384E574F6B53414D79516F504C4B3237394D41564852364A5334303256484555
jwt.access-token-expiration=3600000

# Server Configuration
server.port=8081